language: python
python: 2.7
env:
  - TOX_ENV=py26-django14
  - TOX_ENV=py26-django15
  - TOX_ENV=py26-django16

  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17

  - TOX_ENV=py32-django15
  - TOX_ENV=py32-django16
  - TOX_ENV=py32-django17

  - TOX_ENV=py33-django15
  - TOX_ENV=py33-django16
  - TOX_ENV=py33-django17

  - TOX_ENV=py34-django17

  - TOX_ENV=coverage
install:
  # note: use old version of pip because the new one messes up builds on
  #       django 1.4 & Ubuntu 12.04 (see: #480)
  - pip install pip==6.1.1
  - pip install tox==2.0.2
  - pip freeze
script:
  - tox -e $TOX_ENV -v -r
